@server=http://localhost:4004
@username=alice
@password=


### Books
# @name Books_GET
GET {{server}}/odata/v4/catalog-draft/Books
Authorization: Basic {{username}}:{{password}}


### Books Drafts GET
# @name Books_Drafts_GET
GET {{server}}/odata/v4/catalog-draft/Books?$filter=isDeleted eq true
Authorization: Basic {{username}}:{{password}}


### Books Draft POST
# @name Books_Draft_POST
POST {{server}}/odata/v4/catalog-draft/Books
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": 26478537,
  "title": "title-26478537",
  "stock": 17,
  "isDeleted": false,
  "deletedAt": "2020-06-09T15:00:00.000Z"
}


### Result from POST request above
@draftID={{Books_Draft_POST.response.body.$.ID}}


### Books Draft PATCH
# @name Books_Draft_Patch
PATCH {{server}}/odata/v4/catalog-draft/Books(ID={{draftID}},IsActiveEntity=false)
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "title": "title-26478537",
  "stock": 17,
  "isDeleted": false,
  "deletedAt": "2020-06-09T15:00:00.000Z"
}


### Books Draft Prepare
# @name Books_Draft_Prepare
POST {{server}}/odata/v4/catalog-draft/Books(ID={{draftID}},IsActiveEntity=false)/CatalogDraftService.draftPrepare
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{}


### Books Draft Activate
# @name Books_Draft_Activate
POST {{server}}/odata/v4/catalog-draft/Books(ID={{draftID}},IsActiveEntity=false)/CatalogDraftService.draftActivate
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{}

###
DELETE {{server}}/odata/v4/catalog-draft/Books(ID={{draftID}},IsActiveEntity=true)