@server=http://localhost:4004
@username=alice
@password=


### Books
# @name Books_GET
GET {{server}}/odata/v4/catalog/Books?$filter=isDeleted eq true
Authorization: Basic {{username}}:{{password}}


### Books
# @name Books_POST
POST {{server}}/odata/v4/catalog/Books
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": 23786543,
  "title": "title-23786543",
  "stock": 35
}


### Books
# @name Books_DELETE
DELETE {{server}}/odata/v4/catalog/Books/23786543
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
